version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  my-app:
    image: 630437092685.dkr.ecr.us-east-2.amazonaws.com/ibt-student:latest
    depends_on:
      - mongodb
    ports:
      - 3000:3000
volumes:
  mongo-data:
    driver: local


