apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 630437092685.dkr.ecr.us-east-2.amazonaws.com/ibt-student:k1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          env:
            - name: mongoUser
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: mongoPassword
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: mongoUrl
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
      imagePullSecrets:
        - name: regcred



---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
